### ISSUE TITLE
Is the kareldb server not work for kafka with sasl security?

### ISSUE THREAD

**Issue by lizhanhong1988** [rayokota/kareldb#1]
my kafka clusters use sasl_plain,  and  the server start unsuccessfully.
The kafka version is 2.2.1.
The logs is as follows: 

[2019-09-26 16:41:05,061] INFO KafkaCacheConfig values: 
        kafkacache.bootstrap.servers = [192.168.3.206:9092]
        kafkacache.client.id = kareldb-_tables
        kafkacache.enable.offset.commit = false
        kafkacache.group.id = kareldb
        kafkacache.init.timeout.ms = 300000
        kafkacache.sasl.kerberos.kinit.cmd = /usr/bin/kinit
        kafkacache.sasl.kerberos.min.time.before.relogin = 60000
        kafkacache.sasl.kerberos.service.name = 
        kafkacache.sasl.kerberos.ticket.renew.jitter = 0.05
        kafkacache.sasl.kerberos.ticket.renew.window.factor = 0.8
        kafkacache.sasl.mechanism = PLAIN
        kafkacache.security.protocol = SASL_PLAINTEXT
        kafkacache.ssl.cipher.suites = 
        kafkacache.ssl.enabled.protocols = TLSv1.2,TLSv1.1,TLSv1
        kafkacache.ssl.endpoint.identification.algorithm = 
        kafkacache.ssl.key.password = [hidden]
        kafkacache.ssl.keymanager.algorithm = SunX509
        kafkacache.ssl.keystore.location = 
        kafkacache.ssl.keystore.password = [hidden]
        kafkacache.ssl.keystore.type = JKS
        kafkacache.ssl.protocol = TLS
        kafkacache.ssl.provider = 
        kafkacache.ssl.trustmanager.algorithm = PKIX
        kafkacache.ssl.truststore.location = 
        kafkacache.ssl.truststore.password = [hidden]
        kafkacache.ssl.truststore.type = JKS
        kafkacache.timeout.ms = 60000
        kafkacache.topic = _tables
        kafkacache.topic.num.partitions = 1
        kafkacache.topic.replication.factor = 3
 (io.kcache.KafkaCacheConfig:347)
[2019-09-26 16:41:05,071] INFO Initializing Kafka cache kareldb-_tables with broker endpoints SASL_PLAINTEXT://192.168.3.206:9092  (io.kcache.KafkaCache:141)
[2019-09-26 16:41:05,109] INFO Validating topic _tables (io.kcache.KafkaCache:274)
[2019-09-26 16:41:05,117] WARN The replication factor of the topic _tables is less than the desired one of 3. If this is a production environment, it's crucial to add more brokers and increase the replication factor of the topic. (io.kcache.KafkaCache:300)
[2019-09-26 16:41:05,220] INFO Initialized last consumed offset to {0=-1} (io.kcache.KafkaCache:551)
[2019-09-26 16:41:05,221] INFO KafkaTopicReader thread started for kareldb-_tables. (io.kcache.KafkaCache:553)
[2019-09-26 16:41:05,240] INFO During init or sync, processed 0 records from topic _tables (io.kcache.KafkaCache:565)
[2019-09-26 16:41:05,243] INFO Starting (io.kcache.utils.ShutdownableThread:59)
[2019-09-26 16:41:05,256] INFO Starting leader election... (io.kareldb.server.KarelDbMain:60)
[2019-09-26 16:46:05,277] ERROR Server died unexpectedly:  (io.kareldb.server.KarelDbMain:70)
io.kareldb.server.leader.KarelDbElectionException: Timed out waiting for join group to complete
        at io.kareldb.server.leader.KarelDbLeaderElector.init(KarelDbLeaderElector.java:235)
        at io.kareldb.server.KarelDbMain.main(KarelDbMain.java:62)

**Comment by rayokota** [comment]
@lizhanhong1988 , thanks for reporting this.  Please try release 0.1.5 and let me know how it goes.

**Comment by lizhanhong1988** [comment]
it works fine now。 O(∩_∩)O
