### ISSUE TITLE
java.lang.NoClassDefFoundError: org/apache/omid/tso/Panicker

### ISSUE THREAD

**Issue by VladMl** [rayokota/kareldb#2]
Getting the error when I create a connection to an Embedded DB following by the example on the main page.

Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/omid/tso/Panicker
	at io.kareldb.KarelDbEngine.init(KarelDbEngine.java:118)
	at io.kareldb.schema.SchemaFactory.create(SchemaFactory.java:37)
	at org.apache.calcite.model.ModelHandler.visit(ModelHandler.java:282)
	at org.apache.calcite.model.JsonCustomSchema.accept(JsonCustomSchema.java:45)
	at org.apache.calcite.model.ModelHandler.visit(ModelHandler.java:208)
	at org.apache.calcite.model.ModelHandler.<init>(ModelHandler.java:100)
	at org.apache.calcite.jdbc.Driver$1.onConnectionInit(Driver.java:104)
	at org.apache.calcite.avatica.UnregisteredDriver.connect(UnregisteredDriver.java:139)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:208)

**Comment by rayokota** [comment]
That class is in `org.apache.omid:omid-tso-server-hbase2.x`.  Are you using the Maven dependency to build your project?

**Comment by VladMl** [comment]
I'm using Gradle. Added the dependency and the error has gone. Thanks for the quick response!
